FROM node:16

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /code

EXPOSE 3000

RUN npm i -g @nestjs/cli

ARG USER_ID
ARG GROUP_ID

ENV USER_ID=$USER_ID
ENV GROUP_ID=$GROUP_ID
ENV USER_ID=${USER_ID:-1001}
ENV GROUP_ID=${GROUP_ID:-1001}

RUN addgroup --gid ${GROUP_ID} clug
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} --gid ${GROUP_ID} clug

RUN chown -Rf clug:clug /code

ENTRYPOINT ["tail", "-f", "/dev/null"]