version: '3.7'

services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: .Clug-123
      POSTGRES_DB: clug-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - "db_data:/var/lib/postgresql/data"
  
  # localstack-s3:
  #   image: localstack/localstack:latest
  #   container_name: localstack-s3
  #   ports:
  #     - '4566:4566'
  #   environment:
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #     - AWS_DEFAULT_REGION=eu-west-1 
  #     - EDGE_PORT=4566
  #     - SERVICES=s3
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - ./.localstack:/tmp/localstack
  #     - ./docker/aws:/docker-entrypoint-initaws.d
        
volumes:
  db_data: