name: Backend CI

on:
  push:
    paths: 
      - 'packages/backend/**'
    branches: [ master ]
  pull_request:
    paths: 
      - 'packages/backend/**'
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - working-directory: ./packages/backend
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test