name: Backend CI

on:
  push:
    paths: 
      - './packages/backend/**'
    branches: [ master, develop ]
  pull_request:
    paths: 
      - './packages/backend/**'
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./packages/backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test